name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2

#qualquer push dispara os testes
# Com o git, adicione todas suas mudanças para a área de staging (git add .)
# Faça um commit com a mensagem Create cypress project (git commit -m "Create cypress project")
# Envie suas mudanças locais para seu fork remoto no GitHub (git push origin main)
# Vá até o GitHub e veja sua mudança disparando o pipeline (e se tudo der certo, veja seus testes passando)